version: '3.8'

services:
  # Smart home API
  smart-home-api:
    image: markostreichde/smart-home-api:latest
    container_name: smart-home-api
    restart: always
    ports:
      - "8081:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}=value
  
  # Smart home APP
  smart-home-app:
    image: markostreichde/smart-home-app:latest
    container_name: smart-home-app
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - ./config.prod.js:/usr/share/nginx/html/config.js

  # Update images continously
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
